openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_healthCheck
      parameters: []
      responses:
        '200':
          description: ''
  /contratista:
    get:
      operationId: ContratistasController_encontrarContratista
      summary: Consulta proveedor
      parameters:
        - name: id
          required: true
          in: query
          example: '1234567890'
          schema:
            type: string
      responses:
        '200':
          description: ''
info:
  title: Proveedores API MID
  description: API
  version: '1.0'
  contact: {}
tags:
  - name: API
    description: ''
servers: []
components:
  schemas: {}
