import { PersonaNaturalDto } from './dto/persona-natural.dto';
import { PersonaJuridicaDto } from './dto/persona-juridica.dto';

export const informacionPersonaNatural: PersonaNaturalDto[] = [
  {
    TipoDocumento: {
      Id: 7,
      ClaseParametro: 'Tipo Documento',
      ValorParametro: 'CÉDULA DE CIUDADANÍA',
      DescripcionParametro: 'Tipo de Documento aceptado por la DIAN',
      Abreviatura: 'CC',
    },
    Id: '112233',
    DigitoVerificacion: 0,
    PrimerApellido: 'III',
    SegundoApellido: 'III',
    PrimerNombre: 'KKK',
    SegundoNombre: 'KKK',
    Cargo: '',
    IdPaisNacimiento: 143,
    Perfil: {
      Id: 18,
      ClaseParametro: 'Tipo Perfil',
      ValorParametro: 'ASISTENCIAL',
      DescripcionParametro: '',
      Abreviatura: '',
    },
    Profesion: '',
    Especialidad: '',
    MontoCapitalAutorizado: 0,
    Genero: 'FEMENINO',
    GrupoEtnico: 'AFRODESCENDIENTES',
    ComunidadLgbt: false,
    CabezaFamilia: false,
    PersonasACargo: false,
    NumeroPersonasACargo: 0,
    EstadoCivil: 'VIUDO',
    Discapacitado: true,
    TipoDiscapacidad: 'MENTAL',
    DeclaranteRenta: false,
    MedicinaPrepagada: false,
    ValorUvtPrepagada: 0,
    CuentaAhorroAfc: false,
    NumCuentaBancariaAfc: '',
    IdEntidadBancariaAfc: 0,
    InteresViviendaAfc: 0,
    DependienteHijoMenorEdad: false,
    DependienteHijoMenos23Estudiando: false,
    DependienteHijoMas23Discapacitado: false,
    DependienteConyuge: false,
    DependientePadreOHermano: false,
    IdNucleoBasico: 49207,
    IdArl: 0,
    IdEps: 53,
    IdFondoPension: 112,
    IdCajaCompensacion: 26,
    FechaExpedicionDocumento: '2024-06-10T00:00:00Z',
    IdCiudadExpedicionDocumento: 3064,
  },
  {
    TipoDocumento: {
      Id: 7,
      ClaseParametro: 'Tipo Documento',
      ValorParametro: 'CÉDULA DE CIUDADANÍA',
      DescripcionParametro: 'Tipo de Documento aceptado por la DIAN',
      Abreviatura: 'CC',
    },
    Id: '111111111',
    DigitoVerificacion: 9,
    PrimerApellido: 'PRUEBA1',
    SegundoApellido: 'PRUEBA1',
    PrimerNombre: 'PRUEBA1',
    SegundoNombre: 'PRUEBA1',
    Cargo: '',
    IdPaisNacimiento: 112,
    Perfil: {
      Id: 21,
      ClaseParametro: 'Tipo Perfil',
      ValorParametro: 'PROFESIONAL ESPECIALIZADO',
      DescripcionParametro: '',
      Abreviatura: '',
    },
    Profesion: 'INGENIERO',
    Especialidad: 'ESPECIALISTA EN GESTIÓN DE PROYECTOS TIC',
    MontoCapitalAutorizado: 0,
    Genero: 'MASCULINO',
    GrupoEtnico: 'INDIGENAS',
    ComunidadLgbt: false,
    CabezaFamilia: true,
    PersonasACargo: false,
    NumeroPersonasACargo: 0,
    EstadoCivil: 'SOLTERO',
    Discapacitado: false,
    TipoDiscapacidad: '',
    DeclaranteRenta: true,
    MedicinaPrepagada: false,
    ValorUvtPrepagada: 0,
    CuentaAhorroAfc: false,
    NumCuentaBancariaAfc: '',
    IdEntidadBancariaAfc: 0,
    InteresViviendaAfc: 0,
    DependienteHijoMenorEdad: false,
    DependienteHijoMenos23Estudiando: false,
    DependienteHijoMas23Discapacitado: false,
    DependienteConyuge: false,
    DependientePadreOHermano: false,
    IdNucleoBasico: 830,
    IdArl: 0,
    IdEps: 8,
    IdFondoPension: 24,
    IdCajaCompensacion: 0,
    FechaExpedicionDocumento: '2010-06-29T00:00:00Z',
    IdCiudadExpedicionDocumento: 96,
  },
  {
    TipoDocumento: {
      Id: 13,
      ClaseParametro: 'Tipo Documento',
      ValorParametro: 'PASAPORTE',
      DescripcionParametro: 'Tipo de Documento aceptado por la DIAN',
      Abreviatura: 'PAS',
    },
    Id: '112110735',
    DigitoVerificacion: 3,
    PrimerApellido: 'DELGADO',
    SegundoApellido: 'MARTEN',
    PrimerNombre: 'JUAN',
    SegundoNombre: 'MIGUEL',
    Cargo: '',
    IdPaisNacimiento: 101,
    Perfil: {
      Id: 22,
      ClaseParametro: 'Tipo Perfil',
      ValorParametro: 'NO APLICA',
      DescripcionParametro: '',
      Abreviatura: '',
    },
    Profesion: '',
    Especialidad: '',
    MontoCapitalAutorizado: 0,
    Genero: '',
    GrupoEtnico: 'NO APLICA',
    ComunidadLgbt: false,
    CabezaFamilia: false,
    PersonasACargo: false,
    NumeroPersonasACargo: 0,
    EstadoCivil: 'CASADO',
    Discapacitado: false,
    TipoDiscapacidad: '',
    DeclaranteRenta: false,
    MedicinaPrepagada: false,
    ValorUvtPrepagada: 0,
    CuentaAhorroAfc: false,
    NumCuentaBancariaAfc: '',
    IdEntidadBancariaAfc: 0,
    InteresViviendaAfc: 0,
    DependienteHijoMenorEdad: false,
    DependienteHijoMenos23Estudiando: false,
    DependienteHijoMas23Discapacitado: false,
    DependienteConyuge: false,
    DependientePadreOHermano: false,
    IdNucleoBasico: 0,
    IdArl: 0,
    IdEps: 45,
    IdFondoPension: 119,
    IdCajaCompensacion: 0,
    FechaExpedicionDocumento: '2020-09-18T00:00:00Z',
    IdCiudadExpedicionDocumento: 795,
  },
  {
    TipoDocumento: {
      Id: 7,
      ClaseParametro: 'Tipo Documento',
      ValorParametro: 'CÉDULA DE CIUDADANÍA',
      DescripcionParametro: 'Tipo de Documento aceptado por la DIAN',
      Abreviatura: 'CC',
    },
    Id: '9123456',
    DigitoVerificacion: 6,
    PrimerApellido: 'L',
    SegundoApellido: 'J',
    PrimerNombre: 'N',
    SegundoNombre: 'M',
    Cargo: '',
    IdPaisNacimiento: 112,
    Perfil: {
      Id: 18,
      ClaseParametro: 'Tipo Perfil',
      ValorParametro: 'ASISTENCIAL',
      DescripcionParametro: '',
      Abreviatura: '',
    },
    Profesion: '',
    Especialidad: '',
    MontoCapitalAutorizado: 0,
    Genero: 'MASCULINO',
    GrupoEtnico: 'PALENQUEROS',
    ComunidadLgbt: false,
    CabezaFamilia: false,
    PersonasACargo: false,
    NumeroPersonasACargo: 0,
    EstadoCivil: 'SOLTERO',
    Discapacitado: true,
    TipoDiscapacidad: 'OTRI',
    DeclaranteRenta: false,
    MedicinaPrepagada: false,
    ValorUvtPrepagada: 0,
    CuentaAhorroAfc: false,
    NumCuentaBancariaAfc: '',
    IdEntidadBancariaAfc: 0,
    InteresViviendaAfc: 0,
    DependienteHijoMenorEdad: false,
    DependienteHijoMenos23Estudiando: false,
    DependienteHijoMas23Discapacitado: false,
    DependienteConyuge: false,
    DependientePadreOHermano: false,
    IdNucleoBasico: 49207,
    IdArl: 0,
    IdEps: 56,
    IdFondoPension: 112,
    IdCajaCompensacion: 26,
    FechaExpedicionDocumento: '2024-05-17T00:00:00Z',
    IdCiudadExpedicionDocumento: 96,
  },
  {
    TipoDocumento: {
      Id: 7,
      ClaseParametro: 'Tipo Documento',
      ValorParametro: 'CÉDULA DE CIUDADANÍA',
      DescripcionParametro: 'Tipo de Documento aceptado por la DIAN',
      Abreviatura: 'CC',
    },
    Id: '923456',
    DigitoVerificacion: 6,
    PrimerApellido: '111',
    SegundoApellido: 'H',
    PrimerNombre: 'H',
    SegundoNombre: 'H',
    Cargo: '',
    IdPaisNacimiento: 112,
    Perfil: {
      Id: 22,
      ClaseParametro: 'Tipo Perfil',
      ValorParametro: 'NO APLICA',
      DescripcionParametro: '',
      Abreviatura: '',
    },
    Profesion: '',
    Especialidad: '',
    MontoCapitalAutorizado: 0,
    Genero: '',
    GrupoEtnico: 'PALENQUEROS',
    ComunidadLgbt: false,
    CabezaFamilia: false,
    PersonasACargo: false,
    NumeroPersonasACargo: 0,
    EstadoCivil: 'CASADO',
    Discapacitado: false,
    TipoDiscapacidad: '',
    DeclaranteRenta: false,
    MedicinaPrepagada: false,
    ValorUvtPrepagada: 0,
    CuentaAhorroAfc: false,
    NumCuentaBancariaAfc: '',
    IdEntidadBancariaAfc: 0,
    InteresViviendaAfc: 0,
    DependienteHijoMenorEdad: false,
    DependienteHijoMenos23Estudiando: false,
    DependienteHijoMas23Discapacitado: false,
    DependienteConyuge: false,
    DependientePadreOHermano: false,
    IdNucleoBasico: 0,
    IdArl: 0,
    IdEps: 53,
    IdFondoPension: 113,
    IdCajaCompensacion: 74,
    FechaExpedicionDocumento: '2024-05-21T00:00:00Z',
    IdCiudadExpedicionDocumento: 4143,
  },
  {
    TipoDocumento: {
      Id: 7,
      ClaseParametro: 'Tipo Documento',
      ValorParametro: 'CÉDULA DE CIUDADANÍA',
      DescripcionParametro: 'Tipo de Documento aceptado por la DIAN',
      Abreviatura: 'CC',
    },
    Id: '7123456',
    DigitoVerificacion: 9,
    PrimerApellido: 'B',
    SegundoApellido: 'B',
    PrimerNombre: 'B',
    SegundoNombre: 'B',
    Cargo: '',
    IdPaisNacimiento: 112,
    Perfil: {
      Id: 18,
      ClaseParametro: 'Tipo Perfil',
      ValorParametro: 'ASISTENCIAL',
      DescripcionParametro: '',
      Abreviatura: '',
    },
    Profesion: '',
    Especialidad: '',
    MontoCapitalAutorizado: 0,
    Genero: 'FEMENINO',
    GrupoEtnico: 'NO APLICA',
    ComunidadLgbt: false,
    CabezaFamilia: false,
    PersonasACargo: false,
    NumeroPersonasACargo: 0,
    EstadoCivil: 'SOLTERO',
    Discapacitado: true,
    TipoDiscapacidad: 'DSCPA',
    DeclaranteRenta: false,
    MedicinaPrepagada: false,
    ValorUvtPrepagada: 0,
    CuentaAhorroAfc: false,
    NumCuentaBancariaAfc: '',
    IdEntidadBancariaAfc: 0,
    InteresViviendaAfc: 0,
    DependienteHijoMenorEdad: false,
    DependienteHijoMenos23Estudiando: false,
    DependienteHijoMas23Discapacitado: false,
    DependienteConyuge: false,
    DependientePadreOHermano: false,
    IdNucleoBasico: 49207,
    IdArl: 0,
    IdEps: 53,
    IdFondoPension: 112,
    IdCajaCompensacion: 26,
    FechaExpedicionDocumento: '2024-05-23T00:00:00Z',
    IdCiudadExpedicionDocumento: 3270,
  },
  {
    TipoDocumento: {
      Id: 7,
      ClaseParametro: 'Tipo Documento',
      ValorParametro: 'CÉDULA DE CIUDADANÍA',
      DescripcionParametro: 'Tipo de Documento aceptado por la DIAN',
      Abreviatura: 'CC',
    },
    Id: '1111193324',
    DigitoVerificacion: 2,
    PrimerApellido: 'PEREZ',
    SegundoApellido: 'FERNANDEZ',
    PrimerNombre: 'NATALIA',
    SegundoNombre: '',
    Cargo: '',
    IdPaisNacimiento: 112,
    Perfil: {
      Id: 19,
      ClaseParametro: 'Tipo Perfil',
      ValorParametro: 'TÉCNICO',
      DescripcionParametro: '',
      Abreviatura: '',
    },
    Profesion: ' ASISTENCIA ADMINISTRATIVA',
    Especialidad: '',
    MontoCapitalAutorizado: 0,
    Genero: 'FEMENINO',
    GrupoEtnico: '',
    ComunidadLgbt: false,
    CabezaFamilia: true,
    PersonasACargo: true,
    NumeroPersonasACargo: 2,
    EstadoCivil: 'SOLTERO',
    Discapacitado: false,
    TipoDiscapacidad: '',
    DeclaranteRenta: false,
    MedicinaPrepagada: false,
    ValorUvtPrepagada: 0,
    CuentaAhorroAfc: false,
    NumCuentaBancariaAfc: '',
    IdEntidadBancariaAfc: 0,
    InteresViviendaAfc: 0,
    DependienteHijoMenorEdad: false,
    DependienteHijoMenos23Estudiando: false,
    DependienteHijoMas23Discapacitado: false,
    DependienteConyuge: false,
    DependientePadreOHermano: true,
    IdNucleoBasico: 69,
    IdArl: 0,
    IdEps: 2,
    IdFondoPension: 4,
    IdCajaCompensacion: 0,
    FechaExpedicionDocumento: '2005-01-05T00:00:00Z',
    IdCiudadExpedicionDocumento: 4070,
  },
  {
    TipoDocumento: {
      Id: 7,
      ClaseParametro: 'Tipo Documento',
      ValorParametro: 'CÉDULA DE CIUDADANÍA',
      DescripcionParametro: 'Tipo de Documento aceptado por la DIAN',
      Abreviatura: 'CC',
    },
    Id: '79299055',
    DigitoVerificacion: 6,
    PrimerApellido: 'YEE',
    SegundoApellido: 'DE LA BARCA',
    PrimerNombre: 'CARLOS',
    SegundoNombre: 'ARTURO',
    Cargo: '',
    IdPaisNacimiento: 112,
    Perfil: {
      Id: 21,
      ClaseParametro: 'Tipo Perfil',
      ValorParametro: 'PROFESIONAL ESPECIALIZADO',
      DescripcionParametro: '',
      Abreviatura: '',
    },
    Profesion: 'ECONOMISTA',
    Especialidad: 'GESTION DE PROYECTOS / AVALUOS',
    MontoCapitalAutorizado: 0,
    Genero: 'MASCULINO',
    GrupoEtnico: '',
    ComunidadLgbt: false,
    CabezaFamilia: false,
    PersonasACargo: false,
    NumeroPersonasACargo: 0,
    EstadoCivil: 'CASADO',
    Discapacitado: false,
    TipoDiscapacidad: '',
    DeclaranteRenta: true,
    MedicinaPrepagada: false,
    ValorUvtPrepagada: 0,
    CuentaAhorroAfc: false,
    NumCuentaBancariaAfc: '',
    IdEntidadBancariaAfc: 0,
    InteresViviendaAfc: 0,
    DependienteHijoMenorEdad: false,
    DependienteHijoMenos23Estudiando: false,
    DependienteHijoMas23Discapacitado: false,
    DependienteConyuge: false,
    DependientePadreOHermano: false,
    IdNucleoBasico: 611,
    IdArl: 0,
    IdEps: 45,
    IdFondoPension: 24,
    IdCajaCompensacion: 28,
    FechaExpedicionDocumento: '1982-08-15T00:00:00Z',
    IdCiudadExpedicionDocumento: 96,
  },
  {
    TipoDocumento: {
      Id: 7,
      ClaseParametro: 'Tipo Documento',
      ValorParametro: 'CÉDULA DE CIUDADANÍA',
      DescripcionParametro: 'Tipo de Documento aceptado por la DIAN',
      Abreviatura: 'CC',
    },
    Id: '52086145',
    DigitoVerificacion: 8,
    PrimerApellido: 'RAMIREZ',
    SegundoApellido: 'SANMIGUEL',
    PrimerNombre: 'CAROLINA',
    SegundoNombre: '',
    Cargo: '',
    IdPaisNacimiento: 112,
    Perfil: {
      Id: 21,
      ClaseParametro: 'Tipo Perfil',
      ValorParametro: 'PROFESIONAL ESPECIALIZADO',
      DescripcionParametro: '',
      Abreviatura: '',
    },
    Profesion: 'ABOGADA',
    Especialidad: 'PROCESAL CONSTITUCIONAL',
    MontoCapitalAutorizado: 0,
    Genero: 'FEMENINO',
    GrupoEtnico: '',
    ComunidadLgbt: false,
    CabezaFamilia: false,
    PersonasACargo: false,
    NumeroPersonasACargo: 0,
    EstadoCivil: 'SOLTERO',
    Discapacitado: false,
    TipoDiscapacidad: '',
    DeclaranteRenta: false,
    MedicinaPrepagada: false,
    ValorUvtPrepagada: 0,
    CuentaAhorroAfc: false,
    NumCuentaBancariaAfc: '',
    IdEntidadBancariaAfc: 0,
    InteresViviendaAfc: 0,
    DependienteHijoMenorEdad: false,
    DependienteHijoMenos23Estudiando: false,
    DependienteHijoMas23Discapacitado: false,
    DependienteConyuge: false,
    DependientePadreOHermano: false,
    IdNucleoBasico: 559,
    IdArl: 0,
    IdEps: 6,
    IdFondoPension: 24,
    IdCajaCompensacion: 26,
    FechaExpedicionDocumento: '1994-06-20T00:00:00Z',
    IdCiudadExpedicionDocumento: 96,
  },
  {
    TipoDocumento: {
      Id: 7,
      ClaseParametro: 'Tipo Documento',
      ValorParametro: 'CÉDULA DE CIUDADANÍA',
      DescripcionParametro: 'Tipo de Documento aceptado por la DIAN',
      Abreviatura: 'CC',
    },
    Id: '79571578',
    DigitoVerificacion: 1,
    PrimerApellido: 'PAEZ',
    SegundoApellido: 'MARTINEZ',
    PrimerNombre: 'JOSE ',
    SegundoNombre: 'OSCAR',
    Cargo: '',
    IdPaisNacimiento: 112,
    Perfil: {
      Id: 21,
      ClaseParametro: 'Tipo Perfil',
      ValorParametro: 'PROFESIONAL ESPECIALIZADO',
      DescripcionParametro: '',
      Abreviatura: '',
    },
    Profesion: 'CONTADOR PUBLICO',
    Especialidad: 'GERENCIA Y ADMON FINANCIERA',
    MontoCapitalAutorizado: 0,
    Genero: 'MASCULINO',
    GrupoEtnico: '',
    ComunidadLgbt: false,
    CabezaFamilia: true,
    PersonasACargo: true,
    NumeroPersonasACargo: 2,
    EstadoCivil: 'SOLTERO',
    Discapacitado: false,
    TipoDiscapacidad: '',
    DeclaranteRenta: true,
    MedicinaPrepagada: false,
    ValorUvtPrepagada: 0,
    CuentaAhorroAfc: false,
    NumCuentaBancariaAfc: '',
    IdEntidadBancariaAfc: 0,
    InteresViviendaAfc: 0,
    DependienteHijoMenorEdad: false,
    DependienteHijoMenos23Estudiando: false,
    DependienteHijoMas23Discapacitado: false,
    DependienteConyuge: false,
    DependientePadreOHermano: true,
    IdNucleoBasico: 612,
    IdArl: 0,
    IdEps: 7,
    IdFondoPension: 17,
    IdCajaCompensacion: 0,
    FechaExpedicionDocumento: '1991-08-12T00:00:00Z',
    IdCiudadExpedicionDocumento: 96,
  },
];

export const informacionPersonaJuridica: PersonaJuridicaDto[] = [
  {
    Id: '830108498',
    DigitoVerificacion: 0,
    ProcedenciaEmpresa: 'NACIONAL',
    IdCiudadOrigen: 0,
    CodigoPaisDian: 0,
    CodigoPostal: 0,
    TipoIdentificacionExtranjera: '',
    NumCedulaExtranjeria: 0,
    NumPasaporte: 0,
    IdTipoConformacion: {
      Id: 24,
      Nombre: '',
      Descripcion: '',
      Estado: '',
    },
    MontoCapitalAutorizado: 100000000,
    ExclusividadProducto: false,
    RegimenContributivo: 'COMUN',
    Pyme: false,
    RegistroMercantil: true,
    SujetoRetencion: true,
    AgenteRetenedor: false,
    ResponsableICA: true,
    ResponsableIVA: true,
    Genero: 'NO APLICA',
    NomProveedor:
      'CORPORACIÓN DE TURISMO Y ACTIVIDADES DE COLOMBIA A&C DE COLOMBIA',
  },
  {
    Id: '900621325',
    DigitoVerificacion: 8,
    ProcedenciaEmpresa: 'NACIONAL',
    IdCiudadOrigen: 0,
    CodigoPaisDian: 0,
    CodigoPostal: 0,
    TipoIdentificacionExtranjera: '',
    NumCedulaExtranjeria: 0,
    NumPasaporte: 0,
    IdTipoConformacion: {
      Id: 25,
      Nombre: '',
      Descripcion: '',
      Estado: '',
    },
    MontoCapitalAutorizado: 850000000,
    ExclusividadProducto: false,
    RegimenContributivo: 'COMUN',
    Pyme: true,
    RegistroMercantil: true,
    SujetoRetencion: true,
    AgenteRetenedor: true,
    ResponsableICA: true,
    ResponsableIVA: true,
    Genero: 'NO APLICA',
    NomProveedor: 'DBS GRUPO DE INGENIERIA SAS',
  },
  {
    Id: '900048758',
    DigitoVerificacion: 6,
    ProcedenciaEmpresa: 'NACIONAL',
    IdCiudadOrigen: 0,
    CodigoPaisDian: 0,
    CodigoPostal: 0,
    TipoIdentificacionExtranjera: '',
    NumCedulaExtranjeria: 0,
    NumPasaporte: 0,
    IdTipoConformacion: {
      Id: 25,
      Nombre: '',
      Descripcion: '',
      Estado: '',
    },
    MontoCapitalAutorizado: 34354000,
    ExclusividadProducto: false,
    RegimenContributivo: 'COMUN',
    Pyme: true,
    RegistroMercantil: true,
    SujetoRetencion: true,
    AgenteRetenedor: false,
    ResponsableICA: true,
    ResponsableIVA: true,
    Genero: 'NO APLICA',
    NomProveedor: 'CONSTRUCCIONES E INGENIERÍA CIVIL S.A.S.',
  },
  {
    Id: '900199025',
    DigitoVerificacion: 3,
    ProcedenciaEmpresa: 'NACIONAL',
    IdCiudadOrigen: 0,
    CodigoPaisDian: 0,
    CodigoPostal: 0,
    TipoIdentificacionExtranjera: '',
    NumCedulaExtranjeria: 0,
    NumPasaporte: 0,
    IdTipoConformacion: {
      Id: 25,
      Nombre: '',
      Descripcion: '',
      Estado: '',
    },
    MontoCapitalAutorizado: 4000000000,
    ExclusividadProducto: false,
    RegimenContributivo: 'COMUN',
    Pyme: true,
    RegistroMercantil: true,
    SujetoRetencion: true,
    AgenteRetenedor: false,
    ResponsableICA: true,
    ResponsableIVA: true,
    Genero: 'NO APLICA',
    NomProveedor: 'PRODUCCION DE EVENTOS 911 S.A.S.',
  },
  {
    Id: '860026740',
    DigitoVerificacion: 5,
    ProcedenciaEmpresa: 'NACIONAL',
    IdCiudadOrigen: 0,
    CodigoPaisDian: 0,
    CodigoPostal: 0,
    TipoIdentificacionExtranjera: '',
    NumCedulaExtranjeria: 0,
    NumPasaporte: 0,
    IdTipoConformacion: {
      Id: 6,
      Nombre: '',
      Descripcion: '',
      Estado: '',
    },
    MontoCapitalAutorizado: 500000000,
    ExclusividadProducto: false,
    RegimenContributivo: 'COMUN',
    Pyme: true,
    RegistroMercantil: true,
    SujetoRetencion: true,
    AgenteRetenedor: false,
    ResponsableICA: true,
    ResponsableIVA: true,
    Genero: 'NO APLICA',
    NomProveedor: 'PAPELERIA LOS ANDES LTDA',
  },
  {
    Id: '860517647',
    DigitoVerificacion: 5,
    ProcedenciaEmpresa: 'NACIONAL',
    IdCiudadOrigen: 0,
    CodigoPaisDian: 0,
    CodigoPostal: 0,
    TipoIdentificacionExtranjera: '',
    NumCedulaExtranjeria: 0,
    NumPasaporte: 0,
    IdTipoConformacion: {
      Id: 13,
      Nombre: '',
      Descripcion: '',
      Estado: '',
    },
    MontoCapitalAutorizado: 5000000000,
    ExclusividadProducto: false,
    RegimenContributivo: 'SIMPLIFICADO',
    Pyme: false,
    RegistroMercantil: true,
    SujetoRetencion: false,
    AgenteRetenedor: true,
    ResponsableICA: false,
    ResponsableIVA: true,
    Genero: 'NO APLICA',
    NomProveedor: 'UNIVERSIDAD MANUELA BELTRAN',
  },
  {
    Id: '800239996',
    DigitoVerificacion: 1,
    ProcedenciaEmpresa: 'NACIONAL',
    IdCiudadOrigen: 0,
    CodigoPaisDian: 0,
    CodigoPostal: 0,
    TipoIdentificacionExtranjera: '',
    NumCedulaExtranjeria: 0,
    NumPasaporte: 0,
    IdTipoConformacion: {
      Id: 25,
      Nombre: '',
      Descripcion: '',
      Estado: '',
    },
    MontoCapitalAutorizado: 250000000,
    ExclusividadProducto: true,
    RegimenContributivo: 'COMUN',
    Pyme: false,
    RegistroMercantil: true,
    SujetoRetencion: true,
    AgenteRetenedor: false,
    ResponsableICA: true,
    ResponsableIVA: true,
    Genero: 'NO APLICA',
    NomProveedor: 'GEOAMBIENTE S.A.S',
  },
  {
    Id: '830514155',
    DigitoVerificacion: 0,
    ProcedenciaEmpresa: 'NACIONAL',
    IdCiudadOrigen: 0,
    CodigoPaisDian: 0,
    CodigoPostal: 0,
    TipoIdentificacionExtranjera: '',
    NumCedulaExtranjeria: 0,
    NumPasaporte: 0,
    IdTipoConformacion: {
      Id: 25,
      Nombre: '',
      Descripcion: '',
      Estado: '',
    },
    MontoCapitalAutorizado: 100000000,
    ExclusividadProducto: false,
    RegimenContributivo: 'COMUN',
    Pyme: true,
    RegistroMercantil: true,
    SujetoRetencion: true,
    AgenteRetenedor: false,
    ResponsableICA: true,
    ResponsableIVA: true,
    Genero: 'NO APLICA',
    NomProveedor: 'AUTORUN DISEÑO Y COMUNICACIÓN SAS',
  },
  {
    Id: '900813162',
    DigitoVerificacion: 9,
    ProcedenciaEmpresa: 'NACIONAL',
    IdCiudadOrigen: 0,
    CodigoPaisDian: 0,
    CodigoPostal: 0,
    TipoIdentificacionExtranjera: '',
    NumCedulaExtranjeria: 0,
    NumPasaporte: 0,
    IdTipoConformacion: {
      Id: 25,
      Nombre: '',
      Descripcion: '',
      Estado: '',
    },
    MontoCapitalAutorizado: 5000000000,
    ExclusividadProducto: false,
    RegimenContributivo: 'COMUN',
    Pyme: false,
    RegistroMercantil: true,
    SujetoRetencion: true,
    AgenteRetenedor: false,
    ResponsableICA: true,
    ResponsableIVA: false,
    Genero: 'NO APLICA',
    NomProveedor: 'GRUPO LAVALIT SAS',
  },
  {
    Id: '830047479',
    DigitoVerificacion: 8,
    ProcedenciaEmpresa: 'NACIONAL',
    IdCiudadOrigen: 0,
    CodigoPaisDian: 0,
    CodigoPostal: 0,
    TipoIdentificacionExtranjera: '',
    NumCedulaExtranjeria: 0,
    NumPasaporte: 0,
    IdTipoConformacion: {
      Id: 6,
      Nombre: '',
      Descripcion: '',
      Estado: '',
    },
    MontoCapitalAutorizado: 100000000,
    ExclusividadProducto: false,
    RegimenContributivo: 'COMUN',
    Pyme: true,
    RegistroMercantil: true,
    SujetoRetencion: true,
    AgenteRetenedor: false,
    ResponsableICA: true,
    ResponsableIVA: true,
    Genero: 'NO APLICA',
    NomProveedor: 'REPRESENTACIONES CONSTRUCTIVAS LTDA',
  },
];
